name: check URL accessibility

on: [pull_request]

jobs:
  check_url:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check URL
      id: check_url
      run: |
        cat README.md | grep -E "^\+" | grep -Eo '(http|https)://[^)"]+' | sort | uniq > .patch || true
        ./url_check.sh < .patch
